version: "3.8"

services:
    app:
        build:
            context: .
            args:
                MONGO_URL: ${MONGO_URL}
                MONGO_DB: ${MONGO_DB}
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        environment:
            MONGO_URL: ${MONGO_URL}
            MONGO_DB: ${MONGO_DB}

    mongo:
        image: mongo:4.4
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
